[package]
name = "z-com"
version = "0.1.7"
description = "Z_COM cross-platform communication terminal"
authors = ["Zack(zzk)"]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/ZIKEER/Z_COM"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "z_com_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
parking_lot = "0.12"
probe-rs = "=0.31.0"
serialport = "4"
thiserror = "2"
fs2 = "0.4"
libloading = "0.8"
if-addrs = "0.13"
dunce = "1"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls", "system-proxy"] }
semver = "1"
sha2 = "0.10"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
